# Generated by Django 4.2.5 on 2023-09-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_messages_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='from_user',
            new_name='from_user_id',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='to_user',
            new_name='to_user_id',
        ),
    ]
