# Generated by Django 4.2.5 on 2023-09-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_from_user_messages_from_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='from_user_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='to_user_id',
            new_name='to_user',
        ),
    ]
