# Generated by Django 4.2.5 on 2023-09-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_from_user_id_messages_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2021-01-01T00:00:00Z'),
            preserve_default=False,
        ),
    ]
