# Generated by Django 4.2.5 on 2024-02-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_loses_profile_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='elo',
            field=models.IntegerField(default=800),
        ),
    ]
