# Generated by Django 4.2.5 on 2023-10-08 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=2)),
                ('value', models.IntegerField()),
                ('possible_moves', models.CharField(max_length=255)),
                ('capturing_moves', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PiecesSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knight_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knight_1', to='chess.piece')),
                ('pawn_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pawn_1', to='chess.piece')),
                ('pawn_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pawn_2', to='chess.piece')),
                ('pawn_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pawn_3', to='chess.piece')),
            ],
        ),
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.CharField(max_length=5)),
                ('black_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_pieces', related_query_name='black_pieces', to='chess.piecessetup')),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', related_query_name='black_player', to=settings.AUTH_USER_MODEL)),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', related_query_name='white_player', to=settings.AUTH_USER_MODEL)),
                ('white_pieces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_pieces', related_query_name='white_pieces', to='chess.piecessetup')),
            ],
        ),
    ]
