# Generated by Django 4.2.5 on 2023-10-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackPieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pawn_1', models.JSONField()),
                ('pawn_2', models.JSONField()),
                ('pawn_3', models.JSONField()),
                ('pawn_4', models.JSONField()),
                ('pawn_5', models.JSONField()),
                ('pawn_6', models.JSONField()),
                ('pawn_7', models.JSONField()),
                ('pawn_8', models.JSONField()),
                ('rook_1', models.JSONField()),
                ('rook_2', models.JSONField()),
                ('bishop_1', models.JSONField()),
                ('bishop_2', models.JSONField()),
                ('knight_1', models.JSONField()),
                ('knight_2', models.JSONField()),
                ('queen', models.JSONField()),
                ('kin', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhitePieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pawn_1', models.JSONField()),
                ('pawn_2', models.JSONField()),
                ('pawn_3', models.JSONField()),
                ('pawn_4', models.JSONField()),
                ('pawn_5', models.JSONField()),
                ('pawn_6', models.JSONField()),
                ('pawn_7', models.JSONField()),
                ('pawn_8', models.JSONField()),
                ('rook_1', models.JSONField()),
                ('rook_2', models.JSONField()),
                ('bishop_1', models.JSONField()),
                ('bishop_2', models.JSONField()),
                ('knight_1', models.JSONField()),
                ('knight_2', models.JSONField()),
                ('queen', models.JSONField()),
                ('kin', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='piecessetup',
            name='knight_1',
        ),
        migrations.RemoveField(
            model_name='piecessetup',
            name='pawn_1',
        ),
        migrations.RemoveField(
            model_name='piecessetup',
            name='pawn_2',
        ),
        migrations.RemoveField(
            model_name='piecessetup',
            name='pawn_3',
        ),
        migrations.RenameField(
            model_name='chessgame',
            old_name='current_turn',
            new_name='current_player',
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='black_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_pieces', related_query_name='black_pieces', to='chess.blackpieces'),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='white_pieces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_pieces', related_query_name='white_pieces', to='chess.whitepieces'),
        ),
        migrations.DeleteModel(
            name='PiecesSetup',
        ),
    ]
