# Generated by Django 4.2.5 on 2023-10-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_blackpieces_whitepieces_remove_piecessetup_knight_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blackpieces',
            old_name='kin',
            new_name='king',
        ),
        migrations.RenameField(
            model_name='whitepieces',
            old_name='kin',
            new_name='king',
        ),
    ]
