# Generated by Django 4.2.5 on 2023-10-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_chessgame_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='room_id',
            field=models.CharField(default='111', max_length=5),
            preserve_default=False,
        ),
    ]
