# Generated by Django 4.2.5 on 2023-10-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_rename_kin_blackpieces_king_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgame',
            name='black_piece',
        ),
        migrations.RemoveField(
            model_name='chessgame',
            name='current_player',
        ),
        migrations.RemoveField(
            model_name='chessgame',
            name='white_pieces',
        ),
    ]
