# Generated by Django 4.2.5 on 2023-12-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_alter_blackpieces_bishop_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackpieces',
            name='castled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blackpieces',
            name='king_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blackpieces',
            name='rook_1_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blackpieces',
            name='rook_2_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whitepieces',
            name='castled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whitepieces',
            name='king_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whitepieces',
            name='rook_1_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whitepieces',
            name='rook_2_moved',
            field=models.BooleanField(default=False),
        ),
    ]
