# Generated by Django 4.2.5 on 2023-12-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0006_alter_blackpieces_castled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackpieces',
            name='en_passant_field',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='whitepieces',
            name='en_passant_field',
            field=models.JSONField(null=True),
        ),
    ]
