# Generated by Django 4.2.5 on 2024-01-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0008_chessgame_black_captures_chessgame_black_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_in_queue', models.JSONField(null=True)),
            ],
        ),
    ]
