# Generated by Django 4.2.5 on 2024-01-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0009_playersqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersqueue',
            name='users_in_queue',
            field=models.TextField(default=''),
        ),
    ]
