# Generated by Django 4.2.5 on 2024-01-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0010_alter_playersqueue_users_in_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersqueue',
            name='users_in_queue',
            field=models.TextField(blank=True, default=''),
        ),
    ]
