# Generated by Django 4.2.5 on 2024-03-07 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0011_alter_playersqueue_users_in_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='black_time',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='white_time',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
    ]
