# Generated by Django 4.2.5 on 2024-03-07 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0012_chessgame_black_time_chessgame_white_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='last_move',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 17, 14, 8, 367621, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
