# Generated by Django 4.2.5 on 2024-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0013_chessgame_last_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='last_move',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
