# Generated by Django 4.2.5 on 2024-03-09 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess', '0015_chessgame_waiting_for_first_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_black', to=settings.AUTH_USER_MODEL)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess.chessgame')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
