# Generated by Django 4.2.5 on 2024-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0016_connectedplayers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedplayers',
            name='black_player',
        ),
        migrations.RemoveField(
            model_name='connectedplayers',
            name='white_player',
        ),
        migrations.AddField(
            model_name='connectedplayers',
            name='black_player_pk',
            field=models.TextField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='connectedplayers',
            name='white_player_pk',
            field=models.TextField(blank=True, default='', max_length=5),
        ),
    ]
